import type { Metadata } from "next";
import "./globals.css";
import { Host_Grotesk, Cinzel } from "next/font/google";
import { ReactLenis } from "@/lib/lenis";
import Preloader from "@/components/Preloader/Preloader";
import Navbar from "@/components/Navbar/Navbar";

const hostGrotesk = Host_Grotesk({
  subsets: ["latin"],
  variable: "--font-host-grotesk",
  display: "swap",
});

const cinzel = Cinzel({
  subsets: ["latin"],
  variable: "--font-cinzel",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Bao Bakery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${hostGrotesk.variable} ${cinzel.variable}`}
    >
      <ReactLenis root>
        <body className="antialiased select-none">
          <Preloader />
          {children}
        </body>
      </ReactLenis>
    </html>
  );
}
